package ClientAndServer;


/**
* ClientAndServer/HelloWorldOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Thursday, 23 March 2017 17:05:13 o'clock GMT
*/

public interface HelloWorldOperations 
{
  String hello_world ();
} // interface HelloWorldOperations
