package ClientAndServer;


/**
* ClientAndServer/RelayOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Relay.idl
* Friday, 24 March 2017 10:33:52 o'clock GMT
*/

public interface RelayOperations 
{
  String fetch_message ();
  String reset_status ();
} // interface RelayOperations
